// Generated by scripts/generate-environment.js
export const environment = {
  production: false,
  newsApiKey: '3f181c156e1f42c5a822f56494493750',
  omdbApiKey: '1163afb2',
  countryApiKey: 'f12f942dd5650de64de827dee5dd8b5b',
};
